In [20]:
from sklearn.datasets import load_digits
digit=load_digits()

In [21]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [22]:
#Number of images
len(digit.images)

1797

In [23]:
# Overall data values
digit.data[15]

array([ 0.,  5., 12., 13., 16., 16.,  2.,  0.,  0., 11., 16., 15.,  8.,
        4.,  0.,  0.,  0.,  8., 14., 11.,  1.,  0.,  0.,  0.,  0.,  8.,
       16., 16., 14.,  0.,  0.,  0.,  0.,  1.,  6.,  6., 16.,  0.,  0.,
        0.,  0.,  0.,  0.,  5., 16.,  3.,  0.,  0.,  0.,  1.,  5., 15.,
       13.,  0.,  0.,  0.,  0.,  4., 15., 16.,  2.,  0.,  0.,  0.])

In [24]:
# Value of digit number on the image
digit.target[15]

5

# Logistic Regression

In [25]:
x=digit.data
y=digit.target

In [26]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [27]:
model.fit(x_train,y_train)

C:\Users\mayar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
model.score(x_train,y_train)

1.0

In [29]:
model.score(x_test,y_test)

0.9611111111111111

In [30]:
y_prdicted=model.predict(x_test)
y_prdicted

array([4, 1, 5, 8, 4, 0, 3, 0, 3, 8, 5, 5, 6, 3, 7, 4, 0, 5, 5, 5, 8, 8,
       8, 9, 9, 5, 5, 4, 8, 4, 1, 6, 1, 5, 6, 2, 4, 1, 4, 9, 0, 6, 2, 2,
       8, 0, 7, 8, 7, 8, 0, 4, 2, 5, 1, 9, 0, 9, 7, 6, 7, 1, 9, 7, 3, 2,
       1, 9, 6, 3, 6, 4, 4, 1, 9, 1, 2, 7, 4, 4, 3, 2, 3, 1, 8, 9, 6, 8,
       5, 9, 5, 5, 4, 1, 6, 3, 0, 1, 2, 6, 6, 0, 1, 3, 3, 9, 2, 3, 3, 1,
       4, 0, 8, 9, 8, 4, 3, 0, 5, 8, 5, 3, 0, 1, 7, 8, 6, 1, 6, 3, 6, 3,
       2, 3, 3, 2, 0, 5, 4, 9, 2, 4, 2, 7, 7, 9, 9, 5, 7, 4, 9, 5, 8, 3,
       2, 2, 7, 4, 8, 8, 8, 0, 7, 5, 7, 6, 8, 5, 6, 1, 0, 1, 1, 0, 7, 7,
       4, 1, 5, 4, 5, 2, 0, 2, 6, 0, 8, 2, 2, 9, 3, 4, 9, 9, 2, 1, 1, 9,
       2, 0, 1, 0, 6, 6, 0, 2, 2, 4, 2, 9, 4, 5, 4, 2, 2, 7, 0, 1, 6, 5,
       2, 7, 3, 5, 7, 6, 4, 2, 6, 1, 0, 9, 4, 4, 5, 0, 7, 5, 8, 4, 0, 0,
       7, 2, 0, 8, 3, 5, 1, 5, 0, 1, 8, 9, 4, 6, 3, 0, 9, 0, 4, 3, 0, 1,
       7, 4, 6, 9, 2, 5, 8, 8, 8, 6, 3, 9, 4, 6, 7, 9, 1, 7, 1, 7, 0, 1,
       2, 5, 9, 5, 8, 1, 5, 3, 4, 6, 0, 4, 3, 0, 7,

In [31]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_prdicted)
cm

array([[40,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 33,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  1, 36,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 31,  0,  0,  0,  0,  0,  2],
       [ 0,  2,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 40,  1,  0,  0,  1],
       [ 0,  1,  0,  0,  0,  0, 36,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  1,  0],
       [ 0,  1,  0,  0,  1,  0,  0,  0, 28,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 33]], dtype=int64)

In [32]:
from sklearn.datasets import load_iris
d = load_iris()

In [33]:
dir(d)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [34]:
len(d.data)

150

In [35]:
d.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
x_data=d.data
y_data=d.target

In [38]:
flower=LogisticRegression()
x_dataTrain,x_dataTest,y_dataTrain,y_dataTest=train_test_split(x_data,y_data,test_size=0.2)

In [39]:
flower.fit(x_dataTrain,y_dataTrain)

LogisticRegression()

In [41]:
flower.score(x_dataTrain,y_dataTrain)

0.9666666666666667

In [44]:
flower.score(x_dataTest,y_dataTest)

1.0

In [45]:
y_dataPredicted=flower.predict(x_dataTest)
y_dataPredicted

array([0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 1, 0, 2, 1, 2, 2, 2, 0, 2, 2, 2, 1,
       0, 2, 0, 1, 1, 2, 1, 0])

In [54]:
flower.predict([[12,4,17,6]])

array([2])

In [57]:
flower.predict([[100,6,200,10]])

array([2])